version: '3.8'
services:
  web:
    image: urnau/app1-php:prod-nginx-php-fpm8.2.3
    container_name: web
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PHP_VERSION: '8.2.4-fpm-bullseye'
    labels:
      - traefik.enable=true
      - traefik.http.routers.evolution_api.rule=Host(`wordpress.byteqode.tech`)
      - traefik.http.routers.evolution_api.entrypoints=websecure
      - traefik.http.routers.evolution_api.tls.certresolver=le
      - traefik.http.routers.evolution_api.service=wordpress_wordpress
      - traefik.http.services.evolution_api.loadbalancer.server.port=80
