version: '3.8'
services:
  nproxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '8080:80'
      - '8081:81'
      - '8443:443'
    networks:
      - app
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  web:
    image: urnau/app1-php:prod-nginx-php-fpm8.2.3
    container_name: web
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PHP_VERSION: '8.2.4-fpm-bullseye'
    volumes:
      - .:/var/www/app
    ports:
      - "8080:80" #http
      - "4443:443" #https
networks:
    app:
        driver: bridge
